from fastapi import FastAPI
from pydantic import BaseModel
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI()

# Allow your Expo web app to talk to this Python server
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # In production, lock this down to your app's domain
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ==========================================
# DATA STRUCTURES (What the app sends)
# ==========================================

# 1. Crop Predictor Data
class CropData(BaseModel):
    crop_type: str
    area_hectares: float
    rainfall_mm: float
    fertilizer_kg: float
    temp_celsius: float

# 2. Feed Formulator Data (NEW!)
class FeedData(BaseModel):
    target_protein: str
    ingredients: str


# ==========================================
# ENDPOINTS (The "Rooms" in your server)
# ==========================================

# Room 1: Crop Predictor
@app.post("/api/predict/crop")
async def predict_crop_yield(data: CropData):
    # --- THE TRACER BULLET MODEL ---
    # This is a smart heuristic formula.
    
    base_yield_per_ha = 4.5 if data.crop_type.lower() == 'corn' else 3.8
    
    # Simple multipliers based on optimal conditions
    rain_factor = 1.0 - abs(100 - data.rainfall_mm) / 200  # Prefers ~100mm
    temp_factor = 1.0 - abs(28 - data.temp_celsius) / 40   # Prefers ~28C
    fert_factor = 1.0 + (data.fertilizer_kg / 1000)        # Diminishing returns in real life, simple linear here
    
    # Calculate final yield in Metric Tons
    predicted_tons = (base_yield_per_ha * data.area_hectares) * rain_factor * temp_factor * fert_factor
    
    # Ensure it doesn't drop below 0
    final_prediction = max(0.1, round(predicted_tons, 2))
    
    return {
        "status": "success",
        "crop": data.crop_type,
        "predicted_yield_tons": final_prediction,
        "message": f"Optimal conditions analyzed for {data.area_hectares} hectares."
    }

# Room 2: Feed Formulator (NEW!)
@app.post("/api/formulate")
async def calculate_feed(data: FeedData):
    # --- THE TRACER BULLET MODEL ---
    # Right now, this returns a formatted placeholder string so we can verify 
    # the frontend and backend are communicating perfectly. Later, we will plug 
    # in the real mathematical algorithm here!
    
    mock_recipe = (
        f"✅ Live Server Connection Successful!\n\n"
        f"Target Crude Protein: {data.target_protein}%\n"
        f"Analyzed Ingredients: {data.ingredients}\n\n"
        f"Recommended Starting Mix:\n"
        f"• Corn: 50%\n"
        f"• Soybean Meal: 30%\n"
        f"• Rice Bran: 15%\n"
        f"• Supplements: 5%\n\n"
        f"*(Note: This is an AI placeholder response generated by your Railway server!)*"
    )
    
    return {
        "status": "success",
        "recipe": mock_recipe
    }